services:
  - type: web
    name: album-amor
    env: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
    disk:
      name: uploads
      mountPath: /uploads
      sizeGB: 1 